# This workflow automatically drafts new project releases so it is obvious
# what a current release will look like at any time.
#
# It takes advantage of the labels used in Patina to automatically categorize
# the types of changes in a given release. In addition, the semantic version of
# the code is constantly maintained based on Patina label conventions to ensure
# semantic versioning is followed and a release version is always ready.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# For more information, see:
# https://github.com/release-drafter/release-drafter

name: Update Release Draft

on:
  push:
    branches:
      - main

jobs:
  draft:
    name: Draft Releases

    permissions:
      contents: write
      pull-requests: write

    uses: microsoft/mu_devops/.github/workflows/ReleaseDrafter.yml@v18.0.2
    secrets: inherit
